- name: configure webserver
  hosts: all
  tasks:
  - name: install package
    user:
     name: httpd
     state: present
  - name: create file
    copy:
     content: "this is demo1"
     dest: /var/www/html/index.html
    notify: restart_web
  handlers:
  - name: restart_web
    service:
     name: httpd
     state: restarted
