- name: configure webserver
  hosts: all
  tasks:
  - name: install package
    user:
     name: amit
     state: present
  - name: create website
    copy:
     content: "<h1> THIS IS DONE BY GAURAV <h1>"
     dest: /var/www/html/index.html
